# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('installed_date', models.DateTimeField(blank=True)),
                ('storage_capacity', models.DecimalField(decimal_places=10, max_digits=15)),
                ('storage_free_pct', models.DecimalField(decimal_places=10, max_digits=15)),
                ('storage_capacity_fc', models.DecimalField(decimal_places=10, max_digits=15)),
                ('storage_capacity_nl', models.DecimalField(decimal_places=10, max_digits=15)),
                ('storage_capacity_ssd', models.DecimalField(decimal_places=10, max_digits=15)),
                ('dedupe_ratio', models.DecimalField(decimal_places=10, max_digits=15)),
                ('tdvv_count', models.IntegerField(default=0)),
                ('tdvv_capacity', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
    ]
