# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170323_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemoverview',
            name='installed_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 21, 52, 55, 655743)),
        ),
        migrations.AlterField(
            model_name='systemoverview',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 21, 52, 55, 655559)),
        ),
    ]
